version: "3.9"

services:
  backend:
    container_name: bilinote-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

    depends_on:
      - frontend

  frontend:
    container_name: bilinote-frontend
    build:
      context: .
      dockerfile: BiliNote_frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80"


